### PR TITLE
Fix certificateRenewer to avoid "not a FQDN" error

### LINKED ISSUE #12: Échec de renouvellement
```
/etc/cron.weekly/certificateRenewer:
Checking domain.tld certificate ...
 > Needs to be renewed. Attempting to ...
rm: impossible de supprimer « /tmp/cron-cert-renewer.log »: Aucun fichier ou dossier de ce type
 > An error occured, an email was sent.
mail: invalid option -- 'r'
usage: mail [-dEIinv] [-a header] [-b bcc-addr] [-c cc-addr] [-s subject] to-addr ...
       mail [-dEIiNnv] -f [name]
       mail [-dEIiNnv] [-u user]
```

Donc pas de mail indiquant l'erreur, mais la suppression du log ayant échoué, on retrouve le contenu qui devait être envoyé par mail.

```
Checking for new version...
Upgrading letsencrypt-auto 0.5.0 to 0.7.0...
Replacing letsencrypt-auto...
   cp -p /opt/yunohost/letsencrypt/letsencrypt-auto /tmp/tmp.fvrVZQfKJT/letsencrypt-auto.permission-clone
   cp /tmp/tmp.fvrVZQfKJT/letsencrypt-auto /tmp/tmp.fvrVZQfKJT/letsencrypt-auto.permission-clone
   mv -f /tmp/tmp.fvrVZQfKJT/letsencrypt-auto.permission-clone /opt/yunohost/letsencrypt/letsencrypt-auto
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Requested domain  is not a FQDN
```

L'erreur vient de là:
https://github.com/alexAubin/letsencrypt_ynh/blob/master/sources/certificateRenewer#L123
Dans le fichier de conf `/etc/letsencrypt/renewal/domain.tld.conf`, rien ne matche "domains = ", donc $DOMAINS est vide lors de l'appel de `letsencrypt-auto certonly`

/etc/letsencrypt/renewal/domain.tld.conf contient:

```
# renew_before_expiry = 30 days
cert = /etc/letsencrypt/live/domain.tld/cert.pem
privkey = /etc/letsencrypt/live/domain.tld/privkey.pem
chain = /etc/letsencrypt/live/domain.tld/chain.pem
fullchain = /etc/letsencrypt/live/domain.tld/fullchain.pem
version = 0.8.1

# Options used in the renewal process
[renewalparams]
account = 7c2a659efe7ca46d25f26586d
authenticator = webroot
rsa_key_size = 4096
installer = None
webroot_path = /tmp/letsencrypt-auto,
[[webroot_map]]
domain.tld = /tmp/letsencrypt-auto
```

En exécutant la commande manuellement avec le domaine renseigné, tout c'est bien passé.

### PR DESCRIPTION
**Pull request by JocelynDelalande**
Fix #12 that I was facing myself. It fixed the issue for me.

### CODE REVIEW

**Comment by alexAubin** [comment]
Hi there,

I propagated the fix from @julienmalik from https://github.com/YunoHost-Apps/letsencrypt_ynh instead, as it's less clumsy than my original clumsy parsing of the configuration file.

Closing the pull request, sorry about no propagating it earlier :s

**Comment by JocelynDelalande** [comment]
@alexAubin thanks for reaction :-)

Is there any point at maintaining both /alexAubin/letsencrypt_ynh and YunoHost-Apps/letsencrypt_ynh ?

**Comment by alexAubin** [comment]
Nope, there isn't :).

I'll see how the development of the new tool in python goes and we'll probably move to the Yunohost-Apps repo only.

**Comment by JocelynDelalande** [comment]
> I'll see how the development of the new tool in python goes and we'll probably move to the Yunohost-Apps repo only.

Which python tool ?

For the moment, why not focussing on yunohost-apps version right now ? Current situation leads to confusion and effort-spread IMHO.

Possible solution : 
- stop development at _alexAubin/letsencrypt_ynh_ putting a big fat warning on the GH project description and in the README.
- commit only on _YunoHost-Apps/letsencrypt_ynh_ (if commiting is required).

I tend to prefer "clean it now" solutions than "let's wait for that is not ready yet" ;-)

But that's just my 2 cents of suggestion :-)

**Pull request closed without merging**
